export class FicheMaterielComplexSearch {
    // CHAMPS POSSIBLES POUR LA RECHERCHE :
    // IdFicheMateriel: string;
    // SuiviPar: string;
    // TitreEpisodeVO: string;
    // TitreEpisodeVF: string;
    // isarchived: number;
    // distributeur: string;
    // IdFicheAchat: string;
    // numficheachat: string;
    IdFicheMateriel: number;
    IdFicheAchat: number;
    IdFicheDetail: number;
    Deadline: string;
    SuiviPar: string;
    IdLibstatut: number;
    IdLibEtape: number;
    NumEpisodeProd: number;
    NumEpisodeAB: number;
    TitreEpisodeVF: string;
    TitreEpisodeVO: string;
    IdSupport: string;
    NumProgram: string;
    NumEpisode: number;
    ReceptionAccesLabo: string;
    NomLabo: string;
    CoutLabo: string;
    DateLivraison: string;
    DelaiLivraison: number;
    UniteDelaiLivraison: number;
    DateAcceptation: string;
    DatePremiereDiff: string;
    AccesVF: string;
    Commentaires: string;
    RetourOri: number;
    RetourOriDernierDelai: string;
    IdStatutElementsAnnexes: number;
    UserCreation: string;
    UserModification: string;
    DateCreation: string;
    DateModification: string;
    DateRetourOri: string;
    Renouvellement: number;
    isarchived: number;
    typefiche: string;
    distributeur: string;
    CommentairesDateLivraison: string;
    CommentairesStatutEtape: string;
    numficheachat: string;
    TitreOeuvre: string;
    NomSupport: string;
    chaines: string;
}
