
import { FicheMaterielComplexSearch } from '../models/fiche-materiel-complex-search';

export const complexSearchInit: FicheMaterielComplexSearch = {
    IdFicheMateriel: 0,
    IdFicheAchat: 0,
    IdFicheDetail: 0,
    Deadline: '',
    SuiviPar: '',
    IdLibstatut: 0,
    IdLibEtape: 0,
    NumEpisodeProd: 0,
    NumEpisodeAB: 0,
    TitreEpisodeVF: '',
    TitreEpisodeVO: '',
    IdSupport: '',
    NumProgram: '',
    NumEpisode: 0,
    ReceptionAccesLabo: '',
    NomLabo: '',
    CoutLabo: '',
    DateLivraison: '',
    DelaiLivraison: 0,
    UniteDelaiLivraison: 0,
    DateAcceptation: '',
    DatePremiereDiff: '',
    AccesVF: '',
    Commentaires: '',
    RetourOri: 0,
    RetourOriDernierDelai: '',
    IdStatutElementsAnnexes: 0,
    UserCreation: '',
    UserModification: '',
    DateCreation: '',
    DateModification: '',
    DateRetourOri: '',
    Renouvellement: 0,
    isarchived: 2,
    typefiche: '',
    distributeur: '',
    CommentairesDateLivraison: '',
    CommentairesStatutEtape: '',
    numficheachat: '',
    TitreOeuvre: '',
    NomSupport: '',
    chaines: ''
}
